/*
 * Copyright 2015 Nikos Chalkiadakis.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package source;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;

/**
 *
 * @author Nikos Chalkiadakis
 */
public class AddNotesDialog extends javax.swing.JDialog implements ActionListener {
    private JTextArea initialNotesTextArea;
    
    public AddNotesDialog(JTextArea passedTextArea) {
        super((Frame)null, true);
        initComponents();
        initialNotesTextArea = passedTextArea;
        prepareClasses();
        notesTextArea.setText(initialNotesTextArea.getText());
    }
    
    private void prepareClasses() {
        doneButton.addActionListener(this);
        cancelButton.addActionListener(this);
    }
    
    @Override
    public void actionPerformed(ActionEvent event) {
        if (event.getSource() instanceof JButton) {
            JButton source = (JButton)event.getSource();
            if(source.equals(doneButton)) {
                initialNotesTextArea.setText(notesTextArea.getText());
                this.dispose();
            } else if(source.equals(cancelButton)) {
                this.dispose();
            }
        }
    }

    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code"> 
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        doneButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        notesTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Notes");
        setIconImage(Frame.FRAME_ICON_IMAGE);
        setResizable(false);

        doneButton.setText("Done");

        cancelButton.setText("Cancel");

        notesTextArea.setBackground(new java.awt.Color(204, 255, 204));
        notesTextArea.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        notesTextArea.setLineWrap(true);
        notesTextArea.setToolTipText("");
        notesTextArea.setWrapStyleWord(true);
        notesTextArea.setBorder(javax.swing.BorderFactory.createTitledBorder("Quick Notes"));
        jScrollPane3.setViewportView(notesTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(doneButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelButton)
                        .addGap(5, 5, 5))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doneButton)
                    .addComponent(cancelButton))
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton doneButton;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea notesTextArea;
    // End of variables declaration//GEN-END:variables
    // </editor-fold>
    
}
